# MANAGED by EpiAwarePackageTools.scaffold — do not edit by hand.
# EPIAWARE_MANAGED_PAGES
#
# The docs navigation tree, regenerated on every `scaffold`/`update`. Group
# labels, ordering and placement are the kit's; a package adds its own
# content through `docs/docs_config.jl` (PACKAGE_TUTORIALS, PACKAGE_SECTIONS,
# DEVELOPMENT_EXTEND_PAGE, GETTING_STARTED_FAQ) rather than editing this file
# — any edit made here is overwritten on the next sync (#170/#328/#354).
#
# The Extensions group is written from whatever `[extensions]` the package
# declares in Project.toml, one entry per extension pointing at a page under
# `docs/src/extensions/`; a build drops any entry whose page is missing.
#
# The Benchmarks entry is written with `benchmarks = true`, `ad = true`, or
# both: its own top-level nav group under `docs/src/benchmarks/`, never
# nested inside Tutorials. Performance over time appears with
# `benchmarks = true`, the AD-comparison report with `ad = true`. That report
# is the only AD page the kit writes; the AD-backends tutorial that used to sit
# under Getting started is retired, and its `ad-backends` anchor moved onto the
# report.
#
# Every entry must resolve to a page the package writes or `make.jl`
# generates. Docs about the kit itself live on the kit's own site (#194).

pages = [
    "Home" => "index.md",
    # Authored quickstart, distinct from the README-derived home page. The
    # optional FAQ and the package's own tutorials are both supplied from
    # docs_config.jl.
    "Getting started" => [
        "Overview" => "getting-started/index.md",
    ],
    "API reference" => [
        "Public API" => "lib/public.md",
        "Internal API" => "lib/internals.md",
    ],
    "Benchmarks" => [
        "AD comparison" =>
            "benchmarks/ad-comparison.md",
    ],
    "Development" => [
        "LLM-assisted development process" => "components/llm-process.md",
        "Model components" => "components/model-components.md",
    ],
    # Generated by `make.jl` from the repo's published GitHub releases; the
    # page degrades to a link when they cannot be fetched, so the entry is
    # always safe to keep.
    "Release notes" => "release-notes.md",
]
